### ISSUE TITLE
 KDE text editor "Kate" and image viewer "gwenview"  via the  jasmin_sci 

### ISSUE THREAD

**Issue by dch1fc** [cedadev/extra-sci-packages#25]
Would it be possible to provide the KDE text editor "Kate" and image viewer "gwenview"  via the  jasmin_sci environment?

Those KDE applications are available on the RSG cluster, e.g., apps4.rsg.rl.ac.uk. RSG group asked if the KDE can be made available on JASMIN in particular the sci1 VM /rsg-sci-M sci tenancy. 

For reference: HS#[60101](https://secure.helpscout.net/conversation/2168684457/60101/)

Thank you

**Comment by alaniwi** [comment]
Sorry, these cannot be installed. Installing either of these will add a large number of dependencies, most of the KDE system. These will make the sci machines too much like a desktop environment.

This will be about 100 packages, total ~90MB (although the same set of packages for either, so it is not significantly more if they are both installed).

Then when either of these applications are run, it will start up a number of KDE processes, and not terminate them after the app is closed.

Here is an example of what is left running. (I installed them temporarily on the builder machine.)
```
USER        PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
builder  129760  0.0  0.0  57320  1048 pts/1    S    14:55   0:00 dbus-launch --autolaunch da14788755a047c9ad32ee9b788d5458 --binary-syntax --close-stderr
builder  129761  0.0  0.0  56284  1348 ?        Ss   14:55   0:00 /usr/bin/dbus-daemon --fork --print-pid 5 --print-address 7 --session
builder  129771  0.1  0.1 315428  7880 ?        Ss   14:55   0:00 kdeinit4: kdeinit4 Running...
builder  129773  0.0  0.2 351060 11200 ?        S    14:55   0:00 kdeinit4: klauncher [kdeinit] --fd=8
builder  129780  0.5  0.3 428436 14288 ?        S    14:55   0:00 kdeinit4: kded4 [kdeinit]
builder  129791  0.0  0.0  12428  1276 ?        S    14:55   0:00 /usr/libexec/gam_server
builder  129822  1.0  0.4 836512 18332 ?        Sl   14:55   0:00 /bin/kactivitymanagerd
```

If the KDE libs are installed, then these processes are also started when other apps are run, which in themselves can also be run without KDE -- for example emacs.

Unfortunately it won't be acceptable for this to happen for potentially large numbers of users on the sci machines.

We already have the `display` viewers and various editors available on JASMIN.

Obviously tenancy admins with root access in their tenancy can install their choice apps, but these will added to jasmin-sci.
